version: "3"
services:
  client:
    build:
      context: ./docker-fullstack-app
      dockerfile: Dockerfile
    volumes:
      - ./docker-fullstack-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=http://server:8000
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
