version: "3"
services:
  client:
    build:
      context: .
      dockerfile: docker-fullstack-app/Dockerfile
    volumes:
      - ./docker-fullstack-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=http://server:8000
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
