name: CI/CD Pipeline for simple-docker-fullstack-app

on:
  push:
    paths:
      - "simple-docker-fullstack-app/**"
  pull_request:
    paths:
      - "simple-docker-fullstack-app/**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd simple-docker-fullstack-app
          npm install

      - name: Run tests
        run: |
          cd simple-docker-fullstack-app
          npm test
